/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pdvmvcxwlmikmwspczdp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkdm12Y3h3bG1pa213c3BjemRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxOTE1OTksImV4cCI6MjEwNDc2NzU5OX0.r9WiXgGGjXohqhm-3sevF1_D8MeB2YbIuPt-yQgTko0"